name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build, lint and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - name: Run linting
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: run lint
      - name: Run unit tests
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: test
